### ISSUE TITLE
Support for JupyterLab 2.1

### ISSUE THREAD

**Issue by fzimmermann89** [jupyterlab/jupyterlab-hdf5#30]
Hi,

are there any plans to publish an update that's compatible with JLab >=2.0 ?

Thanks :)

**Comment by pablooriol2** [comment]
I second this. Just installed Jupyterlab and got the following error

![Screenshot 2020-05-01 at 12 48 36](https://user-images.githubusercontent.com/32930813/80803963-ad37b880-8bab-11ea-8735-48015ece19d8.png)

I reinstalled Jupyterlab with version 2.0 but still get the same error message. Quite inconvenient as I was very much looking forward to using the viewer in jupyterlab! There aren't that many HDF viewers out there..

**Comment by snmhas** [comment]
I am also looking forward to have this extension with the latest version of Jupyterlab. Is there nay progress?

**Comment by nitrocalcite** [comment]
I attempted to simply hack `config.json` and rename `lumino`, but with no luck.  As a longtime notebook user but new lab user, I did not expect to find that this apparently official extension is currently bricked.  I was also rather disappointed that both the current state and future of this extension is unclear.

**Comment by athornton** [comment]
Adding my voice here: I too would like to have an HDF5 viewer in current and future JupyterLabs.

**Comment by cnydw** [comment]
I tried to update my local clone to make it work with JL 2.1+, and found out except for updating `@phosphor` libraries with `@lumino`, the dependencies
```
"@jupyterlab/dataregistry": "^3.0.0",
"@jupyterlab/dataregistry-extension": "^3.0.0",
```
don't support JL 2.1+ yet, which was brought up in https://github.com/jupyterlab/jupyterlab-data-explorer/issues/138

I installed the master branch of jupyterlab-data-explorer (which supports JL 2.1) and tried to install jupyterlab-hdf5 using NPM local dependencies
```
"@jupyterlab/dataregistry": "file:../jupyterlab-data-explorer/packages/dataregistry",
"@jupyterlab/dataregistry-extension": "file:../jupyterlab-data-explorer/packages/dataregistry-extension"
```
But I encountered the error
```
npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /github/jupyterlab-data-explorer/packages/dataregistry-extension/node_modules/@types/react
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/github/jupyterlab-data-explorer/packages/dataregistry-extension/node_modules/@types/react'
```

Seems it relates to the jupyterlab-data-explorer packaging structure (node_modules in the root folder, then the individual packages in /packages)

Any suggestions on how to proceed with my local installation? I would love to help update the hdf5 extension to support JL 2.1+.

**Comment by loichuder** [comment]
@cnydw, following your tries, I managed to build the extension on JupyterLab 2.1 by installing the [jupyterlab-data-explorer](https://github.com/jupyterlab/jupyterlab-data-explorer) extensions from the master branch, updating all `@jupyterlab` dependencies in `package.json` and replacing `@phosphor` by `@lumino`.

I also had to fix some `IRegistry` imports.

The resulting extension (https://github.com/loichuder/jupyterlab-hdf5/tree/jupyter2.1) is then available in my JupyterLab instance but I get the `Directory not found` error described in https://github.com/jupyterlab/jupyterlab-hdf5/issues/29 when clicking on hdf5 files.

I tried on JupyterLab 2.2 and this time, I do not get the `Directory not found` error but I am unable to explore any data. I get blank pages instead of data grids (see below) and I get `DOMException: An attempt was made to use an object that is not, or is no longer, usable` in the browser console.
![image](https://user-images.githubusercontent.com/42204205/89914166-ea710500-dbf4-11ea-9867-7fb8ffdc19cb.png)

**Comment by telamonian** [comment]
The latest v0.4.0 release now includes support for juptyerlab 2.x (tested with the latest jlab v2.2.7 release).

@fzimmermann89 @pablooriol2 @snmhas @nitrocalcite @athornton @cnydw @loichuder Please try out the standard jupyterlab-hdf install:

```
pip install jupyterlab_hdf
jupyter labextension install @jupyterlab/hdf5
```

and let me know if you run into any further troubles in a fresh issue
