### ISSUE TITLE
Support of compression filters

### ISSUE THREAD

**Issue by loichuder** [jupyterlab/jupyterlab-hdf5#69]
Thanks to _h5py_, [most compression filters](https://docs.h5py.org/en/stable/high/dataset.html#filter-pipeline) are supported out of the box :tada:

At ESRF, we usually use the bitshuffle filter that isn't directly supported by _h5py_ leading to `500` errors when trying to fetch compressed datasets. 

Importing the [hdf5plugin module](https://pypi.org/project/hdf5plugin/) in the file handling the reading of the dataset would allow to support bitshuffle in addition to other compression filters.

@telamonian Would you agree to add it to the Python project dependencies ?

**Comment by telamonian** [comment]
I'm hesitant to add the `hdf5plugin` py module to the project requirements, since it's a large-ish package (~11 Mb for the tarball) that isn't needed by most users. Instead, i'd say the correct solution would be for users at ESRF (and wherever else the extra filters are needed) to use a slightly modified version of the install instructions:

```
pip install jupyterlab_hdf
pip install hdf5plugin
...
```

We can a note to the README about the extra filters and optionally installing `hdf5plugin`
